Notes: Jenkins pipeline
project: crdc-dh
services:
  backend:
    version: main.21
    image: main.21
    buildNumber: '21'
  frontend:
    version: dev.46
    image: dev.46
    buildNumber: '46'
  files:
    version: 1.4.0.21
    image: 1.4.0.21
    buildNumber: '21'
  authn:
    version: 1.0.0.10
    image: 1.0.0.10
    buildNumber: '10'
  authz:
    version: 1.0.0.5
    image: 1.0.0.5
    buildNumber: '5'
