Notes: Jenkins pipeline
project: crdc-dh
services:
  backend:
    version: main.22
    image: main.22
    buildNumber: '22'
  frontend:
    version: dev.48
    image: dev.48
    buildNumber: '48'
  files:
    version: 1.4.0.21
    image: 1.4.0.21
    buildNumber: '21'
  authn:
    version: 1.0.0.12
    image: 1.0.0.12
    buildNumber: '12'
  authz:
    version: 1.0.0.6
    image: 1.0.0.6
    buildNumber: '6'
